### ISSUE TITLE
Some new ports

### ISSUE THREAD

**Issue by traincrisis** [SamTheGamer39/MinecraftRailroadBlocks#23]
**Describe the feature you'd like**
I would like that the versions for minecraft 1.19.2 forge and 1.18.2 to be added, because i want to use it with the Create mod to decorate my railway built with the Create mod.

**Is your feature request related to a problem? Please describe if applicable.**
I'm always frustrated that there is only version of this mod for 1.19.2 fabric but not forge

**Describe alternatives you've considered**

**Additional context**

**Comment by SamTheGamer39** [comment]
There are already versions of this mod available for 1.19.2 and 1.18.2 on Forge. You can download any of the available mod versions at [Modrinth](https://modrinth.com/mod/railroad-blocks/versions), [CurseForge (for Forge only)](https://www.curseforge.com/minecraft/mc-mods/railroad-blocks-forge/files), and [this GitHub repository](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases).

The following versions are available for Minecraft 1.19.2 with Forge:
- [v0.3.3](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.3)

The following versions are available for Minecraft 1.18.2 with Forge:
- [v0.3.3](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.3)
- [v0.3.2](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.2)

That being said, I am planning on updating the 1.19.2 and 1.18.2 versions of the mod to v0.4.0 in the future, however, the differences between the two versions are minor. A version for 1.19.3+ with Forge is also a possibility.

**Comment by SamTheGamer39** [comment]
There are already versions of this mod available for 1.19.2 and 1.18.2 on Forge. You can download any of the available mod versions at [Modrinth](https://modrinth.com/mod/railroad-blocks/versions), [CurseForge (for Forge only)](https://www.curseforge.com/minecraft/mc-mods/railroad-blocks-forge/files), and [this GitHub repository](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases).

The following versions are available for Minecraft 1.19.2 with Forge:
- [v0.3.3](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.3)

The following versions are available for Minecraft 1.18.2 with Forge:
- [v0.3.3](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.3)
- [v0.3.2](https://github.com/SamTheGamer39/MinecraftRailroadBlocks/releases/tag/v0.3.2)

That being said, I am planning on updating the 1.19.2 and 1.18.2 versions of the mod to v0.4.0 in the future, however, the differences between the two versions are minor. A version for 1.19.3+ with Forge is also a possibility.
